#!/bin/bash

echo "\x1B[33m>>MAP00 achepurn.filler vs $1\x1B[0m"
counter=1
while [ $counter -le 5 ]
do
./filler_vm -f maps/map00 -p2 $1 -p1 ./achepurn.filler | ./visual -t
((counter++))
done
echo "\x1B[33m>>MAP01 achepurn.filler vs $1\x1B[0m"
counter=1
while [ $counter -le 5 ]
do
./filler_vm -f maps/map01 -p2 $1 -p1 ./achepurn.filler | ./visual -t
((counter++))
done
echo "\x1B[33m>>MAP02 achepurn.filler vs $1\x1B[0m"
counter=1
while [ $counter -le 5 ]
do
./filler_vm -f maps/map02 -p2 $1 -p1 ./achepurn.filler | ./visual -t
((counter++))
done